language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t martynovdm/fib-react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true martynovdm/fib-react-test npm test
after_success:
  - docker build -t martynovdm/fib-client ./client
  - docker build -t martynovdm/fib-nginx ./nginx
  - docker build -t martynovdm/fib-server ./server
  - docker build -t martynovdm/fib-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push martynovdm/fib-client
  - docker push martynovdm/fib-nginx
  - docker push martynovdm/fib-server
  - docker push martynovdm/fib-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'fib-complex'
  env: 'Fibcomplex-env'
  bucket_name: 'elasticbeanstalk-us-east-1-115127334025'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
